name: Java CI with Maven

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Download Selenium Server
        run: |
          SELENIUM_VERSION="4.0.0-alpha-2"
          wget -O selenium-server-standalone.jar "https://github.com/SeleniumHQ/selenium/releases/download/selenium-${SELENIUM_VERSION}/selenium-server-standalone-${SELENIUM_VERSION}.jar"

      - name: Download Chromedriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d .

      - name: Start Selenium Hub
        run: |
          java -jar selenium-server-standalone.jar -role hub -port 4444 &
          sleep 5

      - name: Start Selenium Node
        run: |
          java -Dwebdriver.chrome.driver=./chromedriver -jar selenium-server-standalone.jar -role node -hub http://localhost:4444/grid/register -port 5555 &
          sleep 5

      - name: Run WorkTests
        run: mvn -B package --file pom.xml

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure set up
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: /home/runner/work/Simbir_Test/Simbir_Test/target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Set permissions for Allure
        run: sudo chmod -R 777 /home/runner/work/Simbir_Test/Simbir_Test/target/allure-results

      - name: Compile allure Reports
        run: mvn allure:report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history